import { prisma } from "@/lib/prisma"
import { getImageProvider } from "@/lib/providers/image"
import { downloadAndUpload } from "@/lib/storage/r2"
import { visualProfileToPromptFragment, VisualProfileSchema } from "@/lib/schemas/visual-profile"
import type { PipelineContext } from "../types"

const R2_CONFIGURED = !!(process.env.S3_ENDPOINT && process.env.S3_ACCESS_KEY_ID && process.env.S3_BUCKET)

/**
 * Step 11b: Auto-generate character portraits for characters that don't have one yet.
 * Only runs when generateImages is true.
 */
export async function generateMissingPortraits(ctx: PipelineContext): Promise<PipelineContext> {
  if (!ctx.request.generateImages || !ctx.normalizedRequest?.resolvedCharacters.length) {
    ctx.log.push({ step: "generate-portraits", status: "skipped" })
    return ctx
  }

  const start = Date.now()
  let generated = 0

  for (const char of ctx.normalizedRequest.resolvedCharacters) {
    // Check if character already has a portrait
    const template = await prisma.characterTemplate.findUnique({
      where: { id: char.templateId },
      select: { portraitAssetId: true, name: true, essence: true, visualProfile: true },
    })

    if (!template || template.portraitAssetId) continue // already has portrait

    // Build portrait prompt
    let portraitDescription: string
    const rawProfile = template.visualProfile
    if (rawProfile) {
      const parsed = VisualProfileSchema.safeParse(rawProfile)
      if (parsed.success) {
        portraitDescription = visualProfileToPromptFragment(template.name, parsed.data)
      } else {
        const essence = template.essence as Record<string, unknown>
        portraitDescription = `${template.name}: ${essence.appearance ?? essence.personality ?? "a character"}`
      }
    } else {
      const essence = template.essence as Record<string, unknown>
      portraitDescription = `${template.name}: ${essence.appearance ?? essence.personality ?? "a character"}`
    }

    // Use series art style if available
    let artStyleFragment = "Illustrated in a cozy, whimsical children's book style with soft colors and rounded forms."
    const instance = await prisma.characterInstance.findFirst({
      where: { characterTemplateId: char.templateId },
      select: { seriesId: true },
    })
    if (instance) {
      const artLink = await prisma.seriesArtStyleLink.findFirst({
        where: { seriesId: instance.seriesId },
        include: { artStylePreset: true },
      })
      if (artLink) {
        const keywords = artLink.artStylePreset.styleKeywords as string[]
        const medium = artLink.artStylePreset.medium
        artStyleFragment = `Art style: ${keywords.join(", ")}${medium ? `. Medium: ${medium}` : ""}. Maintain this exact style.`
      }
    }

    // Extract age from visual profile to ensure it's explicit in the prompt
    const profileAge = (template.visualProfile as Record<string, unknown>)?.physicalDescription
      ? ((template.visualProfile as Record<string, Record<string, unknown>>).physicalDescription?.age as string) ?? ""
      : ""
    const ageClause = profileAge ? ` The character is ${profileAge} — depict them at exactly this age, do not age them up or down.` : ""

    const prompt = `Character portrait for a children's bedtime storybook. ${portraitDescription}.${ageClause} Soft, warm lighting. Gentle expression. Centered portrait composition, slight three-quarter view. ${artStyleFragment} No text. No background clutter — simple, warm gradient or soft bokeh background.`

    try {
      const imageProvider = getImageProvider()
      const result = await imageProvider.generate({
        prompt,
        negativePrompt: "scary, dark, violent, realistic photo, text, watermark, signature, extra fingers, distorted face",
        metadata: { assetType: "character_portrait", characterId: char.templateId },
      })

      let finalUrl = result.url
      let finalStorageKey = result.storageKey

      if (R2_CONFIGURED && result.url) {
        try {
          const storageKey = `portraits/${char.templateId}/${Date.now()}.png`
          await downloadAndUpload(result.url, storageKey)
          finalStorageKey = storageKey
          finalUrl = storageKey
        } catch {
          // Fall back to ephemeral URL
        }
      }

      const imageAsset = await prisma.imageAsset.create({
        data: {
          name: `${template.name} Portrait`,
          assetType: "character_portrait",
          characterTemplateId: char.templateId,
          storageKey: finalStorageKey,
          url: finalUrl,
          prompt,
          negativePrompt: "scary, dark, violent, realistic photo, text, watermark, signature, extra fingers, distorted face",
          provider: result.provider,
          model: result.model,
          width: 1024,
          height: 1024,
          metadata: { autoGenerated: true },
        },
      })

      await prisma.characterTemplate.update({
        where: { id: char.templateId },
        data: { portraitAssetId: imageAsset.id },
      })

      generated++
    } catch (err) {
      ctx.errors.push({
        step: "generate-portraits",
        critical: false,
        message: `Portrait generation failed for ${template.name}: ${(err as Error).message}`,
      })
    }
  }

  ctx.log.push({
    step: "generate-portraits",
    status: generated > 0 ? "completed" : "skipped",
    durationMs: Date.now() - start,
  })

  return ctx
}
